// Code generated by mockery v1.0.0. DO NOT EDIT.

package persistence

import (
	context "context"

	model "github.com/a-faceit-candidate/userservice/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MockCRUDObserver is an autogenerated mock type for the CRUDObserver type
type MockCRUDObserver struct {
	mock.Mock
}

// OnCreate provides a mock function with given fields: _a0, _a1
func (_m *MockCRUDObserver) OnCreate(_a0 context.Context, _a1 *model.User) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnDelete provides a mock function with given fields: _a0, _a1
func (_m *MockCRUDObserver) OnDelete(_a0 context.Context, _a1 string) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// OnUpdate provides a mock function with given fields: _a0, _a1
func (_m *MockCRUDObserver) OnUpdate(_a0 context.Context, _a1 *model.User) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.User) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
